# ===========================================
# PROD 운영 환경
# ===========================================
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.primushome.gabia.io:3306/dbprimushome?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: primushome
    password: vmflajtm12@@

upload:
  base:
    dir: /web/upload/

site:
  url: https://primusproperty.co.kr

logging:
  level:
    com.prims: INFO
    org.mybatis: WARN
