# ===========================================
# LOCAL 환경
# ===========================================
server:
  port: 38080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my8003.gabiadb.com:3306/kmwown?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: minuk3466
    password: thsqjatndprps12

upload:
  base:
    dir: C:/upload/
